#!/bin/bash
#for esp8266  01,06-E mode=qio
#for esp8266-12-F  mode =dio

#esptool.py --port /dev/ttyUSB0 erase_flash 
#sleep 2

#esp8266-06E
#/var/www/develop/esp8266_toolchain/esptools/esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio  0x0 ./bin/eagle.flash.bin  0x20000  ./bin/eagle.irom0text.bin 

#18=reset  17=program
gpio -g mode 17 output
gpio -g mode 18 output
gpio -g write 17  1
gpio -g write 18  1
sleep 1
gpio -g write 17  0
gpio -g write 18 0
#sleep 1
gpio -g write 18 1
#esp8266-06F
#sleep 1
echo "\nWriting\n"
/var/www/develop/esp8266_toolchain/esptools/esptool.py --port /dev/ttyS0 write_flash --flash_mode dio  0x0 ./bin/eagle.flash.bin  0x20000  ./bin/eagle.irom0text.bin  0x3FC000 ./bin/esp_init_data_default.bin 

gpio -g write 17 1
gpio -g write 18 0
gpio -g write 18 1


#/var/www/develop/esp8266_toolchain/esptools/esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio  0x70000 ./spiff.img

#sleep 2
#esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio  0x3FC000 ./bin/esp_init_data_default.bin 


#esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio  0x0 ./bin/eagle.flash.bin 
#esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio 0x20000  ./bin/eagle.irom0text.bin 


#esptool.py --port /dev/ttyUSB0 read_flash     0x100000 327680  spf.img  

#esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio  0x0 ./bin/boot_v1.6.bin 
#esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio   0x10000  ./bin/upgrade/user1.1024.new.2.bin 


