#!/bin/bash
#for esp8266-01,06-E --flash_mode=qio
#for esp8266-12-F  --flash_mode =dio

echo "\nWriting\n"
/var/www/develop/esp8266_toolchain/esptools/esptool.py --port /dev/ttyUSB0 write_flash --flash_mode dio  0x0 ./bin/eagle.flash.bin  0x20000  ./bin/eagle.irom0text.bin 
#  0x3FC000 ./bin/esp_init_data_default.bin 
